module.exports = {
    FETCH_DONUT_DATA_ERROR: 'FETCH_DONUT_DATA_ERROR',
    FETCH_DONUT_DATA_STARTED: 'FETCH_DONUT_DATA_STARTED',
    FETCH_DONUT_DATA_SUCCEEDED: 'FETCH_DONUT_DATA_SUCCEEDED',
    FETCH_RUBIX_BAR_DATA_STARTED: 'FETCH_RUBIX_BAR_DATA_STARTED',
    UPDATE_RUBIX_BAR_DATA_STARTED: 'UPDATE_RUBIX_BAR_DATA_STARTED',
    FETCH_RUBIX_BAR_DATA_SUCCEEDED: 'FETCH_RUBIX_BAR_DATA_SUCCEEDED',
    FETCH_RUBIX_BAR_DATA_ERROR: 'FETCH_RUBIX_BAR_DATA_ERROR',

}